//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudioPlayerEntities : DbContext
    {
        public AudioPlayerEntities()
            : base("name=AudioPlayerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPlayedSong> tblPlayedSongs { get; set; }
        public virtual DbSet<tblSong> tblSongs { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwPlayedSong> vwPlayedSongs { get; set; }
        public virtual DbSet<vwSong> vwSongs { get; set; }
        public virtual DbSet<vwUser> vwUsers { get; set; }
    }
}
